var mydata = [
    {"name":"Java","logo":"fa-brands fa-java"},
    {"name":"Python","logo":"fa-brands fa-python"},
    {"name":"HTML","logo":"fa-brands fa-html5"},
    {"name":"Vanilla CSS","logo":"fa-brands fa-css3-alt"},
    {"name":"Vanilla JS","logo":"fa-brands fa-js"},
    {"name":"Bootstrap","logo":"fa-brands fa-bootstrap"},
    {"name":"EcmaScript","logo":"fa-solid fa-code"},
    {"name":"API","logo":"fa-solid fa-display"},
    {"name":"Linux","logo":"fa-brands fa-linux"},
    {"name":"NodeJS","logo":"fa-brands fa-node-js"},
    {"name":"OAuth","logo":"fa-brands fa-google"},
    {"name":"Tailwind","logo":"fa-solid fa-file-code"},
    {"name":"ReactJS","logo":"fa-brands fa-react"},
    {"name":"Git","logo":"fa-brands fa-git-alt"},
    {"name":"GitHub","logo":"fa-brands fa-github"},
    {"name":"Flutter","logo":"fa-brands fa-android"},
    {"name":"Arduino","logo":"fa-solid fa-microchip"},
    {"name":"Raspberry Pi","logo":"fa-brands fa-raspberry-pi"},
    {"name":"MongoDB","logo":"fa-solid fa-leaf"},
    {"name":"MySQL","logo":"fa-solid fa-database"},
    {"name":"MS Office","logo":"fa-brands fa-microsoft"},
    {"name":"Wordpress","logo":"fa-brands fa-wordpress"},
]